# Este é um template Mako usado pelo Alembic para gerar scripts de migração de banco de dados.
# Ele define a estrutura para gerenciar a evolução do esquema do banco de dados de forma controlada.

"""Adiciona coluna nome_anexo a Chamado
# Descrição da migração, fornecida pelo desenvolvedor.

Revision ID: e01134c03379
# Identificador único para esta migração, crucial para o controle de versão do esquema.
Revises: f7aaa4687fc9
# Identificador da migração anterior, estabelecendo a ordem das migrações.
Create Date: 2025-10-27 17:55:50.003036
# Data e hora da criação desta migração.

"""
from alembic import op
# 'op' fornece operações de banco de dados (DDL) para modificar o esquema.
import sqlalchemy as sa
# 'sa' (SQLAlchemy) é usado para definir tipos de dados e construções de esquema.


# Identificadores de revisão, usados pelo Alembic para rastrear o histórico.
revision = 'e01134c03379'
# O ID da revisão atual.
down_revision = 'f7aaa4687fc9'
# O ID da revisão para a qual esta migração reverte.
branch_labels = None
# Rótulos de ramificação, úteis para migrações em ambientes de desenvolvimento paralelos.
depends_on = None
# Dependências de outras migrações, garantindo a ordem de execução.


def upgrade():
    # A função 'upgrade' é responsável por aplicar as mudanças no esquema do banco de dados.
    # Ela contém as operações DDL (Data Definition Language) que evoluem o banco de dados
    # para a próxima versão.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chamado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_anexo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # A função 'downgrade' é responsável por reverter as mudanças aplicadas pela função 'upgrade'.
    # É essencial para a reversibilidade do esquema, permitindo desfazer migrações
    # em caso de erros ou necessidade de retornar a um estado anterior.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chamado', schema=None) as batch_op:
        batch_op.drop_column('nome_anexo')

    # ### end Alembic commands ###
