# Este é um template Mako usado pelo Alembic para gerar scripts de migração de banco de dados.
# Ele define a estrutura para gerenciar a evolução do esquema do banco de dados de forma controlada.

"""Aumenta o tamanho da coluna prioridade_Chamado para 20 caracteres
# Descrição da migração, fornecida pelo desenvolvedor.

Revision ID: f7aaa4687fc9
# Identificador único para esta migração, crucial para o controle de versão do esquema.
Revises: d3b76808690c
# Identificador da migração anterior, estabelecendo a ordem das migrações.
Create Date: 2025-10-25 14:08:51.942428
# Data e hora da criação desta migração.

"""
from alembic import op
# 'op' fornece operações de banco de dados (DDL) para modificar o esquema.
import sqlalchemy as sa
# 'sa' (SQLAlchemy) é usado para definir tipos de dados e construções de esquema.


# Identificadores de revisão, usados pelo Alembic para rastrear o histórico.
revision = 'f7aaa4687fc9'
# O ID da revisão atual.
down_revision = 'd3b76808690c'
# O ID da revisão para a qual esta migração reverte.
branch_labels = None
# Rótulos de ramificação, úteis para migrações em ambientes de desenvolvimento paralelos.
depends_on = None
# Dependências de outras migrações, garantindo a ordem de execução.


def upgrade():
    # A função 'upgrade' é responsável por aplicar as mudanças no esquema do banco de dados.
    # Ela contém as operações DDL (Data Definition Language) que evoluem o banco de dados
    # para a próxima versão.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Usuarios')
    op.drop_table('Chamados')
    with op.batch_alter_table('Chamado', schema=None) as batch_op:
        batch_op.alter_column('prioridade_Chamado',
               existing_type=sa.VARCHAR(length=15, collation='Latin1_General_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # A função 'downgrade' é responsável por reverter as mudanças aplicadas pela função 'upgrade'.
    # É essencial para a reversibilidade do esquema, permitindo desfazer migrações
    # em caso de erros ou necessidade de retornar a um estado anterior.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Chamado', schema=None) as batch_op:
        batch_op.alter_column('prioridade_Chamado',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15, collation='Latin1_General_CI_AS'),
               existing_nullable=False)

    op.create_table('Chamados',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('prioridade', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Chamados__3213E83F6C61C529'))
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__Usuarios__3213E83F196A6AC5'))
    )
    # ### end Alembic commands ###
